### PR TITLE
Finish project

### PR DESCRIPTION
**Pull request by yayoamigo**
In this pull request I was able to : 
 -Get metric Data from  API.
- Format Data in thunk to be easily used by the app.
 -Create dynamic route that changes for each continent clicked.
 -Implement searching tool to help users find their target easily.
 -Add transitions and styling to meet the required template.
 -Add tests .
 -Change README to describe the project.

### CODE REVIEW

**Review by FrederickMih — COMMENTED** [review]
## Hi :raising_hand:  @yayoamigo , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a descriptive README.md file. Title of the a PR is not also descriptive 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by yayoamigo** [comment]
hi @FrederickMih sorry but you are mistaken, you can literally see in the commits that I updated the readme file and the pr description has everything I did for the project

**Comment by yayoamigo** [comment]
Screenshot 2023-01-06 160242
Screenshot 2023-01-06 160345
@FrederickMih

**Comment by jerryowusu** [comment]
> hi @FrederickMih sorry but you are mistaken, you can literally see in the commits that I updated the readme file and the pr description has everything I did for the project

Hello @yayoamigo, he is referring to the title of the pr `Setup #1`, since this pr is for the whole project kindly update it to reflect the whole project instead of setup.

**Comment by yayoamigo** [comment]
but he also wrote I didn't have a readme file @jerryowusu

**Comment by jerryowusu** [comment]
> but he also wrote I didn't have a readme file @jerryowusu

Yes. Your readme file is not reflecting because of the way you have named it. Kindly change it to `README.md` instead of` README.old.md`. Due to the naming it does not appear when you change the branch on github.

**Comment by yayoamigo** [comment]
@jerryowusu thanks for clarifying the problem

**Comment by jerryowusu** [comment]
> @jerryowusu thanks for clarifying the problem

one more thing to go. You are suppose to use gitflow ie: the pull request is suppose to be from the dev branch to the main branch. You are currently making the request from the testing branch to dev. Kindly consider updating this.

**Comment by yayoamigo** [comment]
ok this is the link @jerryowusu https://github.com/yayoamigo/Air-polution-app/pull/2

**Comment by FrederickMih** [comment]
> ok this is the link @jerryowusu #2

Hi @yayoamigo, the title of the PR should reflect the project you are developing. **Finish project #1** isn't still a descriptive title. Remember this is a capstone project.

**Comment by FrederickMih** [comment]
Hi @jerryowusu, thanks for clarifying the invalidation above.

**Comment by yayoamigo** [comment]
> Hi @jerryowusu, thanks for clarifying the invalidation above.



> > ok this is the link @jerryowusu #2
> 
> Hi @yayoamigo, the title of the PR should reflect the project you are developing. **Finish project #1** isn't still a descriptive title. Remember this is a capstone project.


How more descriptive can a TITLE be ? it is a title, de description is in the DESCRIPTION of the project

**Comment by yayoamigo** [comment]
I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"

**Comment by FrederickMih** [comment]
> I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"

@yayoamigo approving a project doesn't mean the project meets all requirements. Reviewers are not machines hence they can miss out on something. The title of each PR should always reflect the project(descriptive)

**Comment by yayoamigo** [comment]
> > I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"
> 
> @yayoamigo approving a project doesn't mean the project meets all requirements. Reviewers are not machines hence they can miss out on something. The title of each PR should always reflect the project(descriptive)

I'm guessing you are confuse, the pr title should not descrive the project, it should descrive the purpose of the Pull Request and it should be short, try reading this article to improve as a code reviewer https://climbtheladder.com/10-pull-request-title-best-practices/

**Comment by FrederickMih** [comment]
> > > I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"
> > 
> > 
> > @yayoamigo approving a project doesn't mean the project meets all requirements. Reviewers are not machines hence they can miss out on something. The title of each PR should always reflect the project(descriptive)
> 
> I'm guessing you are confuse, the pr title should not descrive the project, it should descrive the purpose of the Pull Request and it should be short, try reading this article to improve as a code reviewer https://climbtheladder.com/10-pull-request-title-best-practices/

@yayoamigo descriptive here means meaningful not a long text. What's the meaning of **Setup**? Does it have any link with the **air pollution app** you are developing?

**Comment by FrederickMih** [comment]
Screenshot from 2023-01-06 22-41-56

First of all check your link :smile:

**Comment by FrederickMih** [comment]
Hi @yayoamigo from the link you drop above, **setup, finish, and styles** are descriptive titles?? Please let's be serious!

**Comment by yayoamigo** [comment]
> > > > I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"
> > > 
> > > 
> > > @yayoamigo approving a project doesn't mean the project meets all requirements. Reviewers are not machines hence they can miss out on something. The title of each PR should always reflect the project(descriptive)
> > 
> > 
> > I'm guessing you are confuse, the pr title should not descrive the project, it should descrive the purpose of the Pull Request and it should be short, try reading this article to improve as a code reviewer https://climbtheladder.com/10-pull-request-title-best-practices/
> 
> @yayoamigo descriptive here means meaningful not a long text. What's the meaning of **Setup**? Does it have any link with the **air pollution app** you are developing?

Its funny you talk about descriptive when you give a response like "You have submitted a project, that does not contain a descriptive README.md file. Title of the a PR is not also descriptive" with typos, it should be "Title of the a PR is also not descriptive" but you didn't describe the problem. But thanks to @jerryowusu whos a really good code reviewer  I was able to identify what the problem was and fixed it.  I will talk to microverse about your preformance, I don't think you are up to microverse standars

**Comment by FrederickMih** [comment]
@yayoamigo, let's learn to talk like professionals. What would you tell Microverse about my performance? Because I corrected you? So funny. Moreover, I gave credit to the other reviewer for clarifying the issue. You didn't ask for clarification. You rather argued.

**Comment by yayoamigo** [comment]
> > > > I've seen the Pr titles from all the members in my morning session group and they all have their projects approved with titles like : "dev", "setup", "style"
> > > 
> > > 
> > > @yayoamigo approving a project doesn't mean the project meets all requirements. Reviewers are not machines hence they can miss out on something. The title of each PR should always reflect the project(descriptive)
> > 
> > 
> > I'm guessing you are confuse, the pr title should not descrive the project, it should descrive the purpose of the Pull Request and it should be short, try reading this article to improve as a code reviewer https://climbtheladder.com/10-pull-request-title-best-practices/
> 
> @yayoamigo descriptive here means meaningful not a long text. What's the meaning of **Setup**? Does it have any link with the **air pollution app** you are developing?

You said finish project wasn't descriptive, I agree that setup wasn't but finish project is.

**Comment by yayoamigo** [comment]
> @yayoamigo, let's learn to talk like professionals. What would you tell Microverse about my performance? Because I corrected you? So funny. Moreover, I gave credit to the other reviewer for clarifying the issue. You didn't ask for clarification. You rather argued.
I shouldn't have to ask for clarification if you response had been descriptive, its your job as a code reviewer to point every error in a descriptive way, because it wasnt a problem with the readme file, it was the readme file name rather, so it was an easy fix, you should NOT have to rely on others reviewers to do your job.

**Comment by FrederickMih** [comment]
@yayoamigo wish you all the best.

**Pull request merged**
